#!/bin/bash 

  ######################################################################
 ######################################################################
## Author: Adam Michael Danischewski     
## GitHub: https://github.com/AdamDanischewski/cf
## Created: 2019-11-12
## Version: v1.01
## Last Modified: 2019-11-21
## Issues: If you find any issues emai1 me at <my first name> (dot) 
##         <my last name> (at) gmail (dot) com. 
## 
## Description: cf shell wrapper for /usr/bin/colorfiles
##
## The default system wide cf configuration file is located at: 
## /etc/cf/cf_default.conf
## 
## User defined configurations should be placed (not installed by def.): 
## ~/.config/cf/cf_user.conf
## 
## To customize filename colors copy the default configuration to the 
## user defined location, run cf -C to generate a user config file. 
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
##
## Released under Creative Commons License: CC BY-SA 4.0
## https://creativecommons.org/licenses/by-sa/4.0/
########################################################################
 #######################################################################

VERSION=1.0 
COLORFILES_PROG="/usr/bin/colorfiles"
DEFAULT_CF_CONFIG="/etc/cf/cf_default.conf"
USER_CF_CONFIG="${HOME}/.config/cf/cf_user.conf"
DISCARD_DEV=/dev/random

if expr "X$1" : 'X-[-]*'>"$DISCARD_DEV"; then  
 STARTCOLOR="\033[38;2;"  ## ANSI TrueColor RGB triplet prefix 
 ENDCOLOR="\033[0m"       ## End ANSI color 
 ERROR_COLOR="${STARTCOLOR}255;0;0m"
 USAGE_COLOR1="${STARTCOLOR}0;190;190m"
 USAGE_COLOR2="${STARTCOLOR}108;179;251m"
 USAGE_COLOR3="${STARTCOLOR}215;107;21m"
 USAGE_COLOR4="${STARTCOLOR}206;68;67m"
 USAGE_COLOR5="${STARTCOLOR}110;218;24m"
 USAGE_COLOR6="${STARTCOLOR}218;254;25m"
 USAGE_COLOR7="${STARTCOLOR}218;254;218m"
 GREP_PROG="$(type -P grep)"
 SED_PROG="$(type -P sed)"
 COLUMN_PIPE=$(type -P column) && [[ -n ${COLUMN_PIPE} ]] && COLUMN_PIPE="|column"
 ALIAS_CHK=$"^[^#]*alias ls='_\(\){ /bin/ls -F -1 -A \"\x24@\"[|]cf([|]column)?;};_'"
 USER_CF_DIR="$(dirname "${USER_CF_CONFIG}")"
 if "$GREP_PROG" -Eq '^(-A|--add)$' <<< "${1}"; then   
  if ! "$GREP_PROG" -Pq -- "${ALIAS_CHK}" ~/.bashrc; then 
	cat<<-EOF >> ~/.bashrc
	alias ls='_(){ /bin/ls -F -1 -A "\$@"|cf${COLUMN_PIPE};};_'
	EOF
    printf "%s\n" "Added cf based ls alias to ~/.bashrc." 
    printf "%s\n" "Source ~/.bashrc or start a new bash shell for your new ls to take effect."
  else 
    printf "%s\n" "Alias already present in ~/.bashrc."
  fi 
  if ! "$GREP_PROG" -Pq -- "${ALIAS_CHK}" ~/.zshrc; then 
	cat<<-EOF >> ~/.zshrc
	alias ls='_(){ /bin/ls -F -1 -A "\$@"|cf${COLUMN_PIPE};};_'
	EOF
    printf "%s\n" "Added cf based ls alias to ~/.zshrc." 
    printf "%s\n" "Source ~/.zshrc or start a new zsh shell for your new ls to take effect."
  else 
   printf "%s\n" "Alias already present in ~/.zshrc."
  fi   
  exit 0
 elif "$GREP_PROG" -Eq '^(-C|--create)$' <<< "${1}"; then 
  if [[ ! -f "$USER_CF_CONFIG" ]]; then 
   "$(type -P mkdir)" -p "${USER_CF_DIR}" 
   printf "${USAGE_COLOR2}%s${ENDCOLOR}\n" "Writing ${USER_CF_CONFIG} ..."
   ERROR_MESG=$("$SED_PROG" '1!{$!s/^\([^#]*\)\(colormap.*\)/#&/}' "${DEFAULT_CF_CONFIG}" 2>&1 > "$USER_CF_CONFIG")
   if (($?==0)); then 
    printf "${USAGE_COLOR3}%s${ENDCOLOR}\n" "Done! Manually edit ${USER_CF_CONFIG} according to your preferences." 
   else 
    printf "${ERROR_COLOR}%s${ENDCOLOR}\n" "*** Error: Could not write ${USER_CF_CONFIG}" 
    printf "${ERROR_COLOR}%s${ENDCOLOR}\n" "Error mesg: ${ERROR_MESG}" 
   fi
  else 
   printf "${USAGE_COLOR2}%s${ENDCOLOR}\n" "User configuration file already exists, not clobbering: ${USER_CF_CONFIG} ..."   
   printf "${USAGE_COLOR5}%s${ENDCOLOR}\n" "** If you want a new config remove/rename ${USER_CF_CONFIG} and re-run."   
  fi
  exit 0
 elif "$GREP_PROG" -Eq '^(-R|--remove)$' <<< "${1}"; then 
  if [[ -f ~/.bashrc ]] && "$GREP_PROG" -Pq -- "${ALIAS_CHK}" ~/.bashrc; then 
      ## Remove our alias whether created with column or not. 
    "$SED_PROG" -ri -- '\,^[^#]*alias ls=\x27_\(\)\{ /bin/ls -F -1 -A "\x5c\x24\x5c\x40"\|cf([|]column)?;};_\x27,d' ~/.bashrc 
     printf "%s\n" "Removed cf based ls alias, for user (${USER}), from ~/.bashrc."     
  fi 
  if [[ -f ~/.zshrc ]] && "$GREP_PROG" -Pq -- "${ALIAS_CHK}" ~/.zshrc; then 
      ## Remove our alias whether created with column or not. 
    "$SED_PROG" -ri -- '\,^[^#]*alias ls=\x27_\(\)\{ /bin/ls -F -1 -A "\x5c\x24\x5c\x40"\|cf([|]column)?;};_\x27,d' ~/.zshrc 
     printf "%s\n" "Removed cf based ls alias, for user (${USER}), from ~/.zshrc."     
  fi 
  exit 0
 elif expr "${1}" : '-ls'>"$DISCARD_DEV"; then   
  shift
  "$(type -P ls)" -F -1 -A "$@"|"$(type -P cf)"|"$(type -P column || type -P cat)"
  printf "\n${USAGE_COLOR3}%s${ENDCOLOR} %s ${USAGE_COLOR6}%s${ENDCOLOR} %s\n" "** Fast, pretty!?" "Run" "cf --add" "to make it permanent and see the"
  printf "${USAGE_COLOR7}%s${ENDCOLOR}%s\n"  "   cf_config man page" ", on how to customize colorings to your preference."
  [[ -z "$@" ]] && printf "${USAGE_COLOR5}%s${ENDCOLOR}\n" "** Also try running 'cf -ls' with your favorite ls options: cf -ls -al /tmp"
  exit 0
 elif "$GREP_PROG" -Eq '^(-V|--version|-[-]?ver)$' <<< "${1}"; then   
  printf "%s\n" "cf version: $VERSION" 
  exit 0
 else   
USAGE=$(cat<<EOF

 ${USAGE_COLOR1}Usage:${ENDCOLOR} ${USAGE_COLOR6}cf${ENDCOLOR} ${USAGE_COLOR2}[-?|-h|-ls|-A|-R|-C|-V]${ENDCOLOR}
   
  ${USAGE_COLOR1}Options:${ENDCOLOR} 
             ${USAGE_COLOR2}-?|-h${ENDCOLOR}  -  ${USAGE_COLOR7}Help${ENDCOLOR} 
               ${USAGE_COLOR2}-ls${ENDCOLOR}  -  ${USAGE_COLOR7}Test drive <ls alias> in current shell${ENDCOLOR} 
          ${USAGE_COLOR2}-A|--add${ENDCOLOR}  -  ${USAGE_COLOR7}Adds <ls alias> to ~/{.bashrc,.zshrc}${ENDCOLOR}  
                        (For Bash/Zsh users.)
       ${USAGE_COLOR2}-R|--remove${ENDCOLOR}  -  ${USAGE_COLOR7}Removes <ls alias> from ~/{.bashrc,.zshrc}${ENDCOLOR}
                        (For Bash/Zsh users.)
       ${USAGE_COLOR2}-C|--create${ENDCOLOR}  -  ${USAGE_COLOR7}Creates user configuration file.${ENDCOLOR}
                        Generates ~/.config/cf/cf_user.conf 
                        then edit (see man cf_config) to your preferences.                       
      ${USAGE_COLOR2}-V|--version${ENDCOLOR}  -  ${USAGE_COLOR7}Prints cf version number.${ENDCOLOR}
  
        ${USAGE_COLOR2}<ls alias>${ENDCOLOR}  -  ${USAGE_COLOR7}alias ls='_(){ /bin/ls -F -1 -A "\$@"|cf|column;};_'${ENDCOLOR}         
           
  ${USAGE_COLOR1}Description:${ENDCOLOR} ${USAGE_COLOR7}colorizes piped in filenames by extension in Truecolor (sRGB)${ENDCOLOR}
  
  ${USAGE_COLOR1}Files:${ENDCOLOR} ${USAGE_COLOR7}System-wide default color mapping config file:${ENDCOLOR} 
          ${DEFAULT_CF_CONFIG}
	     
         ${USAGE_COLOR7}User defined color mapping config (not installed by default):${ENDCOLOR}  
          ~/.config/cf/cf_user.conf
 
  ${USAGE_COLOR3}Note: You are encouraged to script your own aliases/functions w/cf.${ENDCOLOR}  
        ${USAGE_COLOR5}Eg. /bin/ls | cf   
        Eg. find "\$(pwd)" -maxdepth 1 -type f -printf "%T@\\\\t%Tc %f\\\\n" \\ 
             2>/dev/null|sort -n|cut -f 2-|tail -50|cf${ENDCOLOR}
             
EOF
)
builtin echo -e "${USAGE}"
  if "$GREP_PROG" -Eq '^(-h|-\?|-[-]?help)$' <<< "${1}"; then 
    exit 0
  else 
    printf "%s\n" "*** Error: Bad option (\"${1}\")." 
    exit 1
  fi 
 fi 
fi

if [ -f "$USER_CF_CONFIG" ]; then    
 "${COLORFILES_PROG}" -f "${DEFAULT_CF_CONFIG}" -f "$USER_CF_CONFIG"
else 
 "${COLORFILES_PROG}" -f "${DEFAULT_CF_CONFIG}"
fi
exit 0
