.\" Manpage for cf (colorfiles).
.\" Contact adam.danischewski@protonmail.com to correct errors or typos.
.TH CF 1 "14 Nov 2019" "1.0" "User Commands"
.SH NAME
cf \- colors filenames via pipe
.SH SYNOPSIS
cf  [-?|-h|-ls|-A|-R|-C|-V]
.SH DESCRIPTION
.PP
.B
cf 
improves the commandline user experience by adding extensive filename 
.br 
coloring capabilities via pipelines. \fBcf\fP colorizes mapped file extensions
.br 
to a Truecolor sRGB triplet - maintaining consistency across environments.

Additionally \fBcf\fP utilizes the \fIls -F\fP classification option 
format to determine 
.br
whether a file is hidden, directory, executable or symbolic link for specialized 
.br
coloring capabilities including fallback coloring (See
\fIcf_config(1)\fP). To 
.br
maximize the utility of \fBcf\fP's coloring capabilities make sure that your 
.br 
pipelines format filenames accordingly. See the \fIExamples\fP section in this man 
.br
page for an example on coloring \fIfind\fP to the 
.I
ls -F 
classification format. 
.br

.PP
\fBcf\fP colors piped file names by file extension or specialized logic according 
.br
to their respective \fIcolormap["ext"]\fP entry in the system-wide or user-defined 
.br
\fBcf\fP config file.
.br

\fBcf\fP is fairly quick and efficient. Unlike \fIls\fP, which uses the LS_COLORS env 
.br 
variable for determining colors, \fBcf\fP uses hash table lookups in \fIawk\fP resulting
.br 
in a much quicker and efficient color mapping. \fIls\fP in contrast incurs a perfor-
.br 
mance hit of reading the entire LS_COLORS string for each coloring miss. Also 
.br 
\fIls\fP is constrained by ARG_MAX/MAX_ARG_* limits on argument list whereas \fBcf\fP is not. 
.br
.SH OPTIONS
.IP -?|-h 15n
- Help
.IP -ls 15n
- Test drive <ls alias> in current shell. 
.IP -A|--add 15n
- Adds <ls alias> to ~/{.bashrc,.zshrc}
  (For Bash/Zsh users.)
.IP -R|--remove 15n
- Removes <ls alias> from ~/{.bashrc,.zshrc}
  (For Bash/Zsh users.)
.IP -C|--create 15n
- Creates a user-defined configuration file.
  Generates ~/.config/cf/cf_user.conf that the user can edit 
  (see man cf_config) to their preferences.  
.IP -V|--version 15n
- Prints cf version number.
.IP "<ls alias>" 15n
- alias ls='_(){ /bin/ls -F -1 -A "$@"|cf|column;};_'
.SH EXAMPLES 
.PP
The following mimics \fI/bin/ls -F\fP (classify) that \fBcf\fP utilizes to determine how 
.br 
to color special files (hidden, links, directories and executables):  
.sp .09i
 find . -maxdepth 1 \\( -type l -printf "%f@\\n" -o -type d -printf "%f/\\n" \\ 
        -o -executable -printf "%f*\\n" -o -printf "%f\\n" \\)|cf
.br

The following will quickly print files in the current dir, in a star globbing 
.br
shell (eg. Bash/Zsh): 
.sp .09i
 printf "%s\\n" *|cf      
.br
.SH CAVEATS
\fBcf\fP colorizes the rightmost filename, which causes a potential variation between
.br
links that end with \fI@\fP versus expanded links (\fIls -a\fP) containing \fI->\fP. That is the 
.br
intended behavior.
.br

If you get used to using \fBcf\fP you will likely find it difficult not to!!
.SH FILES
.I /etc/cf/cf_default.conf
.\".RS
.sp .01i
 Default system wide configuration file.
.\".RE 
.sp .25i
.I ~/.config/cf/cf_user.conf
.\".RS
.sp .01i
 User configuration file. 
.\".RE
.SH "SEE ALSO"
.RI
cf_config(1)
.SH BUGS
Extensions with spaces are problematic. 
.br 
No known bugs. Report requests, issues and bugs to:
.br
 https://github.com/AdamDanischewski/cf/issues
.SH COPYRIGHT
Copyright ©2019 Adam Danischewski, CC BY-SA 4.0
.br
Creative Commons  - (https://creativecommons.org/licenses/by-sa/4.0/)
.SH AUTHOR
Adam Danischewski <adam.danischewski@protonmail.com>
