.\" Manpage for cf_config (colorfiles).
.\" Contact adam.danischewski@protonmail.com to correct errors or typos.
.TH CF_CONFIG 1 "21 Nov 2019" "1.0" "User Commands"
.SH NAME
cf_config \- cf configuration files
.SH SYNOPSIS
.PP
cf utilizes a system-wide config file and optionally a user-defined   
.br 
config file. 
.br

The system-wide default config file is located at: 
.br 
.BI 
.I /etc/cf/cf_default.conf
.br

.br

The user-defined config file is located at:
.br
.I ~/.config/cf/cf_user.conf
.br 

Both may be edited. 
.br

To start customizing for a user first create a config file using: cf --create
.br 
.SH DESCRIPTION
.PP
\fBcf\fP colors piped file names to a Truecolor sRGB triplet - by file extension 
.br
or optionally specialized logic for hidden, links, directories and executables - 
.br
according to their respective colormap entry in the system-wide or user-defined 
.br
\fBcf\fP config file. 
.br
.PP
The main program is \fI/usr/lib/colorfiles\fP, the system-wide default config 
.br
file is read first and thereafter - if a user-defined config file exists - 
.br
it is read second. Therefore, user-defined config settings take precedence.
.br

.br
* Valid values for colormap["ext"] entries are quoted semicolon 
.br
  separated sRGB triplets or a previously defined colormap entry. 
.br
  "[0-255];[0-255];[0-255]" -or- colormap["ext"] 
.br

.br
* For previously defined colormap["ext"] entries you may utilize any 
.br
  existing uncommented entries in the user or system-wide config file 
.br
  without redeclaring their initialization. For convenience all system 
.br
  default values are included in commented form at the creation of a new
.br 
  user config file (via \fBcf --create\fP). Any system-wide color mappings after 
.br
  the user-defined config file was generated will not be present in the 
.br
  user config file. If you add a default related to a new system-wide 
.br
  default entry it's recommended that you add a comment containing the 
.br
  associated sRGB triplet value.  
.br

.br
* File extensions must be lowercase. \fBcf\fP uses case insensitive 
.br
  matching that relies on lowercasing file extensions. 
.br
  file.JpG -and- file.jpg both match colormap["jpg"]
.br

.br
* File extensions may have two components, the penultimate component 
.br
  can be up to 5 characters long, the final component when a 
.br
  penultimate component exists is up to 5 characters long. 
.br
  For example - if you have a colormap entry colormap["abcde.12345"] then  
.br
  a file named testing.abcde.12345 would match that colormap entry. 
.br
  A file named testing.abcdef.1234 would match colormap["1234"]. 
.br
  A file named testing.a.12345678 would match colormap["12345678"]. 
.br

.br
* If no penultimate component exists the file extension may be up to 
.br
  10 characters long. file.ABCDE12345 matches colormap["abcde12345"]. 
.br

.br
The following functionalities can be turned off by setting their 
.br
respective lookup value to the empty string: eg. colormap["dir"]="" 
.br

.br
* Files ending w/an "@" symbol -or- containing the string "->" within 
.br
  their filename are treated as symbolic links and colored according to 
.br
  the colormap["links"] entry
.br

.br
* Files beginning with a "." are treated as a hidden file and 
.br
  colored according to the colormap["hidden"] entry
.br

.br
* Files ending with a "*" are treated as an executable file and 
.br
  colored according to the colormap["executable"] entry
.br

.br
* Files ending with a "/" are treated as a directory and 
.br
  colored according to the colormap["dir"] entry
.br

.br
The aforementioned above functionalities, except "dir", also have a 
.br
respective fallback entry prefixed with "fb_". For instance - 
.br
colormap["fb_links"] is the fallback entry for colormap["links"]. 
.br

The fallback logic only colors files if an extension match has not 
.br
already been found. The precedence order for fallback logic is 
.br 
executables then hidden then links. 
.br   
.SH TIPS 
You may run \fBcf\fP without options or anything piped in to start a 
.br  
session that will echo back colorings to whatever filenames you type 
.br  
in. This is useful while configuring your custom \fIcf_user.conf\fP file. 
   
.SH CAVEATS
When editing config files make sure that you don't turn off a 
.br
colormap entry and then assign the entry by reference to a new 
.br 
colormap entry. 
.br 
  
.br 
For instance, if in your user config you have a line that looks like:  
.br   
 colormap["hidden"]=""
.br 

Make sure thereafter you don't include a line like: 
.br   
 colormap["fb_hidden"]=colormap["hidden"]  
.br 

If you were expecting the fb_hidden functionality to be turned on and 
.br 
set to a former color value of colormap["hidden"] in the default config. 
.br 

.PP 
The 'BEGIN {' starting at the top and '}' at the end of the config 
.br
files are necessary. This is ultimately an awk program and we only 
.br
want to set the mappings once per run so don't remove them. 
.br 
.PP 
To restore the system-wide default config backup the file to a secure 
.br
known location and copy it back when desired -or- reinstall cf. 
.br
    
.SH FILES
.I /etc/cf/cf_default.conf
.\".RS
.sp .01i
 Default system wide configuration file.
.\".RE 
.sp .25i
.I ~/.config/cf/cf_user.conf
.\".RS
.sp .01i
 User configuration file. 
.\".RE
.SH "SEE ALSO"
.RI
cf(1)
.SH BUGS
Extensions with spaces are problematic. 
.br 
No known bugs. Report requests, issues and bugs to: 
.br
 https://github.com/AdamDanischewski/cf/issues 
.SH COPYRIGHT
Copyright ©2019 Adam Danischewski, CC BY-SA 4.0
.br
Creative Commons  - (https://creativecommons.org/licenses/by-sa/4.0/)
.SH AUTHOR
Adam Danischewski <adam.danischewski@protonmail.com>
